default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: trailing-whitespace

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 5c3f3c61b143a94e9ab5d767ff4d0dc9d6801aa3 # v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg

  - repo: https://github.com/ansible/ansible-lint
    rev: d7cd7cfa2469536527aceaef9ef2ec6f2fb331cb # v25.9.2
    hooks:
      - id: ansible-lint
        language_version: python3.12

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: system
        entry: npx prettier --write
        types_or:
          - json
          - yaml
