[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "homelab"
version = "0.1"
requires-python = ">= 3.10"
dependencies = [
    "pip-tools>=7.5.1",
    "pre-commit>=4.3.0",
]
