[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "homelab"
version = "0.1"
requires-python = ">= 3.11"
dependencies = [
    "ansible-core>=2.19.3",
    "pip-tools>=7.5.1",
    "pre-commit>=4.3.0",
    "pykickstart>=3.67",
]
